### PR TITLE
Determinate solution

### PR DESCRIPTION
**Pull request by GRsni**
Fix file parser, save Distributed Loads to the files. Solves issue #4

### CODE REVIEW

**Comment by kmccullen97** [comment]
Did you test loading a file after saving it?

**Comment by GRsni** [comment]
I believe there's been a between my fork and the local clone I made of the repo. I made the changes inside the determinate-solution branch, but after pulling the project, there's some missing dependencies. Probably going to just delete the local repo and pull it again. Also, since the classes are now empty, this PR is basically useless.

**Comment by kmccullen97** [comment]
Yes the Parser::write() method is now empty, but it does need to be rewritten with code to save the file using the new classes i created (PinSupport, RollerSupport, FixedSupport, PointLoad, Moment, and DistributedLoad).  The distributed load class has changed slightly so this could could work with some changes (names of properties have changed)

**Comment by kmccullen97** [comment]
I have also added a project to the repo. This way we can keep track of what still need to be done.

**Comment by GRsni** [comment]
I've been working on the `Parser::write()` function, but whenever I want to build the project in debug mode, it throws an error saying there's a missing Node.h header, which doesn't make sense because there is no call to load a Node.h header anywhere on the project. Moreover, the error doesn't reference any line in the project code.
However, building the project in profile mode or release mode works perfectly. Any idea why this is happening?

**Comment by kmccullen97** [comment]
That is strange.  I'm not sure a particular solution to that issue but a few times QT Creator has given me weird errors.  What I do is run qmake, then build and run and sometimes the errors go away.

**Comment by GRsni** [comment]
Well that sounds like fun...

**Comment by kmccullen97** [comment]
Just to to build->run qmake and see if that fixes it.

**Comment by GRsni** [comment]
Hey, that worked. Thanks!

**Comment by GRsni** [comment]
Btw, I've realized that to be able to test the write function, I need first to remake the controller interface. Will make a quick prototype just to get going at least.

**Comment by kmccullen97** [comment]
That works.  Or since I wrote the load functionality, you could write up a file load it, and then save and see if it works.  Also before the save function wrote all the information to a single line,  it might be nice to format it in the way that other examples I posted are.

**Comment by GRsni** [comment]
Yeah, having to read a one line file is a pain. I already had started making it write the files in blocks, like the existing examples.

**Pull request closed without merging**
